name = "About Blank"
license = "Apache 2.0"
licenselink = "https://www.apache.org/licenses/LICENSE-2.0"
description = ""
homepage = "https://github.com/schu/about-blank"
tags = []
features = []
min_version = "0.42"

[author]
  name = "Michael Schubert"
  homepage = "https://schu.io"
